### ISSUE TITLE
一些修改意见

### ISSUE THREAD

**Issue by Zhao-yz** [Sandiagal/DoujinFix#2]
1.标题序号调整异常，例如[飴沢狛] ラブミルフィーユ (COMIC快楽天 2019年8月号) [無邪気漢化組][MJK-19-Z1716][無修正]转化失败，提示命名真奇葩
2.希望能够增加一个可选项，保留类似于“中国語”、“中国翻訳”等未知译者的汉化信息
感谢作者能够制作这样一款软件！

**Comment by Sandiagal** [comment]
抱歉才看到
1. 问题在 [MJK-19-Z1716] 上，后续版本会直接删掉这一类标示
2. ok，可以满足你

**Comment by Sandiagal** [comment]
嘿
我新添加了“标示过滤”功能，可以保留“[MJK-19-Z1716]”、“中国翻訳”、“無修正”等标示
可以试试[新版](https://github.com/Sandiagal/DoujinFix/releases/tag/v3.04)，希望你喜欢

**Comment by Zhao-yz** [comment]
收到，您动作真快，十分感谢！

**Comment by Zhao-yz** [comment]
> 嘿
> 我新添加了“标示过滤”功能，可以保留“[MJK-19-Z1716]”、“中国翻訳”、“無修正”等标示
> 可以试试[新版](https://github.com/Sandiagal/DoujinFix/releases/tag/v3.04)，希望你喜欢
向大大您做一个反馈：[無邪気無修宇宙分組] [薬味紅生姜]魔術部の先輩と使い魔の僕 (COMIC アオハ 2019 秋) [無邪気漢化組] [MJK-19-Z1931] [無修正]，这个文件名无法修改，所有带有[無邪気無修宇宙分組]名字的都无法识别，我觉得可以考虑将[無邪気無修宇宙分組]与[無修正]分在一个标签中，后后置，并可以去掉

**Comment by Sandiagal** [comment]
抱歉摸了半年才看到。
無邪気组的命名总是能出点新花样。[無邪気無修宇宙分組] 和 [無邪気漢化組] 在不同位置描述相同的内容，所以正则识别冲突。由于这种问题实在太罕见，还是手动调整名称更便捷。

**Comment by Zhao-yz** [comment]
> 抱歉摸了半年才看到。
> 無邪気组的命名总是能出点新花样。[無邪気無修宇宙分組] 和 [無邪気漢化組] 在不同位置描述相同的内容，所以正则识别冲突。由于这种问题实在太罕见，还是手动调整名称更便捷。

好的，感谢您！因为無邪気组有专门翻无修正的计划，收藏意义比较高，比较喜欢他家翻的本，所以才有这个建议。
