### ISSUE TITLE
BUG？

### ISSUE THREAD

**Issue by Smile8848** [Sandiagal/DoujinFix#5]
[![qEFjD1.png](https://s1.ax1x.com/2022/03/19/qEFjD1.png)](https://imgtu.com/i/qEFjD1)
貌似过滤得有问题

**Comment by Smile8848** [comment]
另外怎么能够只保留无修正的标示 汉化之类去掉呢

**Comment by Sandiagal** [comment]
抱歉回的晚了
你是说要保留 comic 吗，还是原作名不对？
“无修正”一开始就没考虑保留，需要改代码。
汉化的话，记得有预设格式可以调

**Comment by Smile8848** [comment]
> 抱歉回的晚了 你是说要保留 comic 吗，还是原作名不对？ “无修正”一开始就没考虑保留，需要改代码。 汉化的话，记得有预设格式可以调

了解了，保留无修正更好辨别版本。
